---
name: Docker Image CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create config file for kaniko
        run: |
          # github automatically generates the token
          cat <<EOF > config.json
          {
            "auths": {
              "ghcr.io": {
                "auth": "$(echo -n ${{ secrets.REGISTRY_USER }}:${{ secrets.REGISTRY_TOKEN }} | base64)"
              }
            }
          }
          EOF

      # debug from cli:
      # docker run -ti --rm -v `pwd`:/workspace -v `pwd`/config.json:/kaniko/.docker/config.json:ro gcr.io/kaniko-project/executor:latest --dockerfile=Dockerfile --destination=ghcr.io/code-4-penguins/github-actions/my-python-app:latest
      - name: Build the Docker image
        run: |
          docker run \
            -v `pwd`:/workspace \
            -v `pwd`/config.json:/kaniko/.docker/config.json:ro \
            gcr.io/kaniko-project/executor:latest \
              --dockerfile=Dockerfile \
              --context dir:///workspace/ \
              --destination=ghcr.io/code-4-penguins/github-actions/my-python-app:test123
