---
name: Docker Image CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker run \
          -v `pwd`:/workspace \
          -v `pwd`/config.json:/kaniko/.docker/config.json:ro \
          gcr.io/kaniko-project/executor:latest \
          --dockerfile=Dockerfile \
          --context dir:///workspace/ \
          --no-push
          # --destination=https://ghcr.io/code-4-penguins/github-actions/my-python-app:latest
